services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_USERNAME: "$MYSQL_USER"
      SPRING_DATASOURCE_PASSWORD: "$MYSQL_PASSWORD"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/$MYSQL_DATABASE"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

  mysql:
    image: mysql:latest
    container_name: prison_db
    volumes:
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  mysql-data: